# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rahman Qureshi's Blog
email: rahman.a.qureshi@gmail.com
author: Rahman Qureshi
description: "Powered by <a href=\"https://jekyllrb.com/\">Jekyll</a> and <a href=\"https://pages.github.com/\">Github Pages</a>."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rahmanqureshi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rahmanqureshi
facebook_username: rahmanqureshi
instagram_username: rayq95

disqus:
  shortname: rahmanqureshi-github-io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
